// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("bs-platform/lib/js/caml_option.js");

var localStorageNamespace = "phoenixClient/reasonml@authToken";

function loadToken(param) {
  return Caml_option.null_to_opt(localStorage.getItem(localStorageNamespace));
}

function saveToken(token) {
  localStorage.setItem(localStorageNamespace, token);
  return /* () */0;
}

function removeToken(param) {
  localStorage.removeItem(localStorageNamespace);
  return /* () */0;
}

function isLoggedIn(param) {
  var match = localStorage.getItem(localStorageNamespace);
  return match !== null;
}

exports.localStorageNamespace = localStorageNamespace;
exports.loadToken = loadToken;
exports.saveToken = saveToken;
exports.removeToken = removeToken;
exports.isLoggedIn = isLoggedIn;
/* No side effect */
