// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Axios = require("axios");
var React = require("react");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

function user(json) {
  return /* record */[
          /* id */Json_decode.field("id", Json_decode.$$int, json),
          /* name */Json_decode.field("name", Json_decode.string, json),
          /* email */Json_decode.field("email", Json_decode.string, json)
        ];
}

function users(json) {
  return Json_decode.field("data", (function (param) {
                return Json_decode.list(user, param);
              }), json);
}

var Decode = /* module */[
  /* user */user,
  /* users */users
];

var url = "http://localhost:4000/api/users";

function fetchUsers(param) {
  return Axios.get(url).then((function (response) {
                  var users$1 = users(response.data);
                  return Promise.resolve(users$1);
                })).catch((function (_err) {
                return Promise.resolve(undefined);
              }));
}

function str(prim) {
  return prim;
}

var component = ReasonReact.reducerComponent("Users");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1];
              if (typeof match === "number") {
                switch (match) {
                  case 0 : 
                      return React.createElement("div", undefined, "Click to start load Users", React.createElement("button", {
                                      onClick: (function (_event) {
                                          return Curry._1(self[/* send */3], /* LoadUsers */0);
                                        })
                                    }, "Load Users"));
                  case 1 : 
                      return React.createElement("div", undefined, "Loading...");
                  case 2 : 
                      return React.createElement("div", undefined, "Something went wrong!");
                  
                }
              } else {
                return React.createElement("div", undefined, React.createElement("h2", undefined, "Users"), React.createElement("ul", undefined, $$Array.of_list(List.map((function (user) {
                                          return React.createElement("li", {
                                                      key: String(user[/* id */0])
                                                    }, user[/* name */1]);
                                        }), match[0]))));
              }
            }),
          /* initialState */(function (param) {
              return /* NotAsked */0;
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _state) {
              if (typeof action === "number") {
                if (action !== 0) {
                  return /* Update */Block.__(0, [/* Failure */2]);
                } else {
                  return /* UpdateWithSideEffects */Block.__(2, [
                            /* Loading */1,
                            (function (self) {
                                fetchUsers(/* () */0).then((function (result) {
                                        if (result !== undefined) {
                                          return Promise.resolve(Curry._1(self[/* send */3], /* LoadedUsers */[result]));
                                        } else {
                                          return Promise.resolve(Curry._1(self[/* send */3], /* LoadUsersFailed */1));
                                        }
                                      }));
                                return /* () */0;
                              })
                          ]);
                }
              } else {
                return /* Update */Block.__(0, [/* Success */[action[0]]]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.Decode = Decode;
exports.url = url;
exports.fetchUsers = fetchUsers;
exports.str = str;
exports.component = component;
exports.make = make;
/* component Not a pure module */
