// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

function Make(Config) {
  var component = ReasonReact.reducerComponent("Router");
  var make = function (render, _children) {
    return /* record */[
            /* debugName */component[/* debugName */0],
            /* reactClassInternal */component[/* reactClassInternal */1],
            /* handedOffState */component[/* handedOffState */2],
            /* willReceiveProps */component[/* willReceiveProps */3],
            /* didMount */(function (self) {
                var watcherID = ReasonReact.Router[/* watchUrl */1]((function (url) {
                        return Curry._1(self[/* send */3], /* UpdateRoute */[Curry._1(Config[/* toRoute */1], url)]);
                      }));
                return Curry._1(self[/* onUnmount */4], (function (param) {
                              return ReasonReact.Router[/* unwatchUrl */2](watcherID);
                            }));
              }),
            /* didUpdate */component[/* didUpdate */5],
            /* willUnmount */component[/* willUnmount */6],
            /* willUpdate */component[/* willUpdate */7],
            /* shouldUpdate */component[/* shouldUpdate */8],
            /* render */(function (self) {
                return Curry._1(render, /* record */[
                            /* updateRoute */(function (route) {
                                return Curry._1(self[/* send */3], /* UpdateRoute */[route]);
                              }),
                            /* route */self[/* state */1][/* route */0]
                          ]);
              }),
            /* initialState */(function (param) {
                return /* record */[/* route */Curry._1(Config[/* toRoute */1], ReasonReact.Router[/* dangerouslyGetInitialUrl */3](/* () */0))];
              }),
            /* retainedProps */component[/* retainedProps */11],
            /* reducer */(function (action, _state) {
                return /* Update */Block.__(0, [/* record */[/* route */action[0]]]);
              }),
            /* jsElementWrapped */component[/* jsElementWrapped */13]
          ];
  };
  return /* module */[
          /* component */component,
          /* make */make
        ];
}

exports.Make = Make;
/* ReasonReact Not a pure module */
